# Site settings
title: Boulder Community Engagement
email: bboone@codeforamerica.org
description: > # this means to ignore newlines until "baseurl:"
  This site shares the learnings from the community engagement process in Boulder Colorado around a project called Housing Boulder.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://boulderengagement.com" # the base hostname & protocol for your site
twitter_username: boonrs
github_username:  boonrs

# Build settings
markdown: kramdown
